### ISSUE TITLE
Server timezone issue with new version of PHP

### ISSUE THREAD

**Issue by sdk7327** [pylorak/ulogin#8]
When testing I was getting some warnings about using the server time zone and couldn't seem to have changes to the php.ini take effect. I corrected this by adding

```
date_default_timezone_set('America/New_York');
```

to line 2 of Utils.inc.php.

**Comment by sdk7327** [comment]
Looks like this also needs to be added to Nonce.inc.php

**Comment by urban-1** [comment]
Hi, what if you add this to the main config in`config/main.inc.php`. I would assume it is included every time... would that work?

**Comment by sdk7327** [comment]
derp, yeah that probably would have been easier...

(confirmed working)
